config/routes.rb
Rails.application.routes.draw do

  resources :doctors do
    member do
      post :create_nurse
      delete :destroy_nurse
    end
 

    resources :patients do
      member do
        post :create_nurse
        delete :destroy_nurse
        patch :wait_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_patient
        patch :discharge_patient
      end
      collection do
        get :patient_search
      end
    end
  end

  
  resources :medications
  resources :searches
  get 'static_pages/home'

  get 'static_pages/about'

  root 'static_pages#home'
  

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :patient_medications
  has_many :patients, through: :patient_medications

  validates :name, presence: true
  validates :company, presence: true
  validates :adverse_effects, presence: true
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

  def show
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:patient_id]
    @medication = Medication.find params[:id]
  end

  def new
    @medication = Medication.new
    @patients = Patient.all
  end

  def index
    @medications = Medication.all
  end

  def show
    @medication = Medication.find params[:id]
  end

  def create
    @medication = Medication.create medication_params
    @patients = Patient.all
    if @medication.save
      flash[:success] = "Medication added!"
      redirect_to doctors_path
    else
      flash[:danger] = "Incomplete form!"
      render :new
    end
  end

  def edit
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.find params[:patient_id]
    @medication = Medication.find params[:id]
  end

  def update
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.find params[:patient_id]
    @medication = Medications.find params[:id]
    @medication.update medication_params
    redirect_to patient_path
  end

  def destroy
    @medication = Medication.find params[:id]
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:patient_id]
    @medication.delete
    redirect_to patient_path
  end

private
  def medication_params
    params.require(:medication).permit(
      :name,
      :company,
      :adverse_effects,
      patient_ids: []
      )
  end




end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.haml
= form_for [@medication] do |f|
  = f.label :name
  = f.text_field :name
  %bt/
  = f.label :company
  = f.text_field :company
  %br/
  = f.label :adverse_effects
  = f.text_field :adverse_effects
  %br/
  %h5 Prescription for:
  = hidden_field_tag 'medication[patient_ids][]', ''
  - @patients.each do |patient|
    = check_box_tag 'medication[patient_ids][]', patient.id, @medication.patients.include?(patient)
    = patient.first_name
    = patient.last_name
    %br/
  = f.submit

app/views/medications/edit.html.haml
- provide(:pagetitle, 'Edit')
= render 'form'

app/views/medications/new.html.haml
- provide(:pagetitle, 'Add Meds')
%h2 Add Med
= render 'form'

app/views/medications/show.html.haml
%h1 Medication Info
%br
  = link_to "Edit Medication", edit_medication_path(@medication), class: 'btn btn-info'
  = link_to "Delete Medication", medication_path(@medication), method: :delete, class: 'btn btn-danger'
  %br
    %br
      %ul.dl-horizontal
        %dt Name
        %dd= @medication.name
        %dt Company
        %dd= @medication.company
        %dt Adverse Effects
        %dd= @medication.adverse_effects
      %br
        %br/