config/routes.rb
Rails.application.routes.draw do

  resources :doctors do
    member do
      post :create_nurse
      delete :destroy_nurse
    end
 

    resources :patients do
      member do
        post :create_nurse
        delete :destroy_nurse
        patch :wait_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_patient
        patch :discharge_patient
      end
      collection do
        get :patient_search
      end
    end
  end

  
  resources :medications
  resources :searches
  get 'static_pages/home'

  get 'static_pages/about'

  root 'static_pages#home'
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base

  belongs_to :doctor
  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_many :nurses, as: :nurseable

  BLOOD_OPTIONS = [
    "A",
    "A-",
    "A+",
    "B",
    "B-",
    "B+",
    "O",
    "O-",
    "O+"
  ]
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dob, presence: true
  validates :description, presence: true
  validates :gender, presence: true
  validates :blood_type, presence: true

  include Workflow
  workflow do
    state :waiting_room do
      event :wait, transitions_to: :waiting_room
      event :checkup, transitions_to: :mid_checkup
      event :xray, transitions_to: :mid_xray
      event :enter_surgery, transitions_to: :mid_surgery
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end

    state :mid_checkup do
      event :xray, transitions_to: :mid_xray
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end

    state :mid_xray do
      event :pay, transitions_to: :paid
      event :checkup, transitions_to: :mid_checkup
      event :discharge, transitions_to: :discharged
    end

    state :mid_surgery do
      event :pay, transitions_to: :paid
      event :discharge, transitions_to: :discharged
    end

    state :paid do
      event :discharge, transitions_to: :discharged
    end

    state :discharged do
      event :wait, transitions_to: :waiting_room
    end
  end

  #  def self.search(search)
  #   if search
  #     where("first_name LIKE ? OR last_name LIKE?", "%#{search}%", "%#{search}%")
  #   else
  #     scoped
  #   end
  # end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [
    :wait_patient,
    :checkup_patient,
    :xray_patient,
    :surgery_patient,
    :bill_patient,
    :discharge_patient
  ]

  def show
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:id]
    @nurse = Nurse.new
    @medication = @patient.medications
    @nurses = @patient.nurses
  end

  def new
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.new
    @medications = Medication.all
  end

  def create
    @doctor = Doctor.find params[:doctor_id]
    @patient = @doctor.patients.create patient_params
    @medications = Medication.all
    if @patient.save
      flash[:success] = "Welcome to St. Jon's!"
      redirect_to doctor_path(@doctor)
    else
      flash[:danger] = "Form incomplete"
      render :new
    end
  end

  def index
    @patients = Patient.all
    @doctor = Doctor.find params[:doctor_id]
  end

  def edit
    @patient = Patient.find params[:id]
    @medications = @patient.medications
    @doctor = Doctor.find params[:doctor_id]
  end

  def update
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:id]
    @patient.update_attributes patient_params
    redirect_to doctors_path(@doctor)
  end

  def destroy
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:id]
    @patient.delete
    redirect_to doctors_path(@doctor)
  end

  def create_nurse
    @doctor = Doctor.find params[:doctor_id]
    @patient = Patient.find params[:id]
    @nurse = @patient.nurses.create nurse_params
    redirect_to doctor_patient_path(@doctor, @patient)
  end

  def destroy_nurse
    @doctor = Doctor.find params[:doctor_id]
    @nurse = Nurse.find params[:id]
    @nurse.delete
    redirect_to doctor_patient_path(@nurse.nurseable.doctor, @nurse.nurseable)
  end

  def wait_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient.wait!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def checkup_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient.checkup!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def xray_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient.xray!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def surgery_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient.enter_surgery!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def bill_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient.pay!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def discharge_patient
    @doctor = Doctor.find params[:doctor_id]
    @patient.discharge!
    respond_to do |format|
      format.js
      format.html
    end
  end

  def patient_search
    @doctor = Doctor.find params[:doctor_id]
    @patients = Patient.where("first_name LIKE ? OR last_name LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def set_patient
    @patient = Patient.find params[:id]
  end

  def patient_params
    params.require(:patient).permit(
      :first_name,
      :last_name,
      :dob,
      :description,
      :gender,
      :blood_type,
      medication_ids: []
    )
  end

  def nurse_params
    params.require(:nurse).permit(
      :nurse_name,
      )
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_errors.html.haml
- if @patient.errors.any?
  #error_explanation
    %ul
      - @patient.errors.full_messages.each do |msg|
        %li= msg

app/views/patients/_form.html.haml
= form_for [@doctor, @patient] do |p|
  %ul#sign_up_form.list-group
    = render 'errors'
    %li.list-group-item
      %h3= p.label :first_name, class: 'label label-default'
      = p.text_field :first_name
    %br/
    %li.list-group-item
      %h3= p.label :last_name, class: 'label label-default'
      = p.text_field :last_name
    %br/
    %li.list-group-item
      %h3= p.label :Date_of_Birth, class: 'label label-default'
      = p.date_select :dob, start_year: 1900, end_year: 2005
    %br/
    %li.list-group-item
      %h3= p.label :description, class: 'label label-default'
      = p.text_field :description
    %br/
    %li.list-group-item
      %h3= p.label :gender, class: 'label label-default'
      = p.radio_button :gender, 'male'
      Male
      \#{p.radio_button :gender, 'female'}Female
    %br/
    %li.list-group-item
      %h3= p.label :blood_type, class: 'label label-default'
      = p.select :blood_type, options_for_select(Patient::BLOOD_OPTIONS, p.object.blood_type), include_blank: "--- Select ---"
    / = hidden_field_tag 'patient[drug_ids][]', ''
    %li.list-group-item
      - @medications.each do |medication|
        = check_box_tag 'patient[medication_ids][]', medication.id, @patient.medications.include?(medication)
        = medication.name  
    %br/
    %li.list-group-item
      = p.submit "Complete Registration", class: "btn btn-primary"

app/views/patients/_index.html.haml
.row
  .col-md-12.text-center
    %input.patient-search
      = link_to "Search", 'javascript:void(0);', class: "patient-search-submit", doctor_id: @doctor.id
%br
.container.patient-search-stuff
- provide(:pagetitle, 'Patients')
- @patients.each do |patient|
  %dl.dl-horizontal
    %dt First Name
    %dd= link_to patient.first_name, doctor_patient_path(@doctor, patient)
    %dt Last Name
    %dd= patient.last_name
    %dt Date of Birth
    %dd= patient.dob
    %dt Description
    %dd= patient.description
    %dt Gender
    %dd= patient.gender
    %dt Blood Type
    %dd= patient.blood_type
    %br
      %dt= link_to "Edit", edit_doctor_patient_path(@doctor, patient), class: 'btn btn-info'
      %dd= link_to "Delete", doctor_patient_path(@doctor, patient), method: :delete, class: 'btn btn-danger'

app/views/patients/_workflow.html.haml
= @patient.workflow_state
- if @patient.waiting_room?
  = link_to "Begin Intake", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "wait", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Checkup", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "checkup", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Recieve X-Ray", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "xray", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Start Surgery", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "surgery", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Bill Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "bill", doctor_id: @doctor.id, patient_id: @patient.id
- if @patient.mid_checkup?
  = link_to "Recieve X-Ray", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "xray", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Bill Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "bill", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Discharge Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "discharge", doctor_id: @doctor.id, patient_id: @patient.id
- if @patient.mid_xray?
  = link_to "Bill Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "bill", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Discharge Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "discharge", doctor_id: @doctor.id, patient_id: @patient.id
- if @patient.mid_surgery?
  = link_to "Bill Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "bill", doctor_id: @doctor.id, patient_id: @patient.id
  = link_to "Discharge Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "discharge", doctor_id: @doctor.id, patient_id: @patient.id
- if @patient.paid?
  = link_to "Discharge Patient", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "discharge", doctor_id: @doctor.id, patient_id: @patient.id
- if @patient.discharged?
  = link_to "Begin Intake", 'javascript:void(0);', class: 'btn btn-default btn-sm', id: "begin", doctor_id: @doctor.id, patient_id: @patient.id

app/views/patients/bill_patient.js.haml
$(".body-content-stuff").html("#{j(render 'workflow')}")

app/views/patients/checkup_patient.js.haml
$(".body-content-stuff").html("#{j(render 'workflow')}")

app/views/patients/discharge_patient.js.haml
$(".body-content-stuff").html("#{j(render 'workflow')}")

app/views/patients/edit.html.haml
- provide(:pagetitle, 'Edit')
= render 'form'

app/views/patients/index.html.haml
- provide(:pagetitle, 'Patients')
- @patients.each do |patient|
  %dl.dl-horizontal
    %dt First Name
    %dd= link_to patient.first_name, patient_path(patient)
    %dt Last Name
    %dd= patient.last_name
    %dt Date of Birth
    %dd= patient.dob
    %dt Description
    %dd= patient.description
    %dt Gender
    %dd= patient.gender
    %dt Blood Type
    %dd= patient.blood_type
    %br
      %dt= link_to "Edit", edit_patient_path(patient), class: 'btn btn-info'
      %dd= link_to "Delete", patient_path(patient), method: :delete, class: 'btn btn-danger'

app/views/patients/new.html.erb
<% provide(:pagetitle, 'Sign up') %>

<%= render 'form' %>

app/views/patients/patient_search.js.haml
$(".body-content-stuff").html("#{j(render 'index')}")

app/views/patients/surgery_patient.js.haml
$(".body-content-stuff").html("#{j(render 'workflow')}")

app/views/patients/wait_patient.js.haml
$(".body-content-stuff").html("#{j(render 'workflow')}")

app/views/patients/xray_patient.js.haml
$(".body-content-stuff").html("#{j(render 'workflow')}")