config/routes.rb
Rails.application.routes.draw do

  resources :doctors do
    member do
      post :create_nurse
      delete :destroy_nurse
    end
 

    resources :patients do
      member do
        post :create_nurse
        delete :destroy_nurse
        patch :wait_patient
        patch :checkup_patient
        patch :xray_patient
        patch :surgery_patient
        patch :bill_patient
        patch :discharge_patient
      end
      collection do
        get :patient_search
      end
    end
  end

  
  resources :medications
  resources :searches
  get 'static_pages/home'

  get 'static_pages/about'

  root 'static_pages#home'
  

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :patients, dependent: :destroy
  has_many :nurses, as: :nurseable

  validates :doctor_name, presence: true
  validates :specialty, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = if !params[:q].blank?
      Doctor.where("doctor_name LIKE ? OR specialty LIKE?", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      Doctor.all
    end
  end

  def new
    @doctor = Doctor.new
  end

  def show
    @doctor = Doctor.find params[:id]
    @patients = @doctor.patients.where(params[:search])
    @nurse = Nurse.new
    @nurses = @doctor.nurses
    # respond_to do |format|
    #   format.js
    #   format.html
    # end
  end

  def create
    @doctor = Doctor.create doctor_params
    if @doctor.save
      flash[:success] = "Doctor Created!"
      redirect_to doctors_path
    else
      flash[:danger] = "Form incomplete"
      render :new
    end
  end

  def create_nurse
    @doctor = Doctor.find params[:id]
    @nurse = @doctor.nurses.create nurse_params
    redirect_to doctor_path(@doctor)
  end

  def destroy_nurse
    # @doctor = Doctor.find params[:id]
    # @nurses = @doctor.nurses
    @nurse = Nurse.find params[:id]
    # @nurse = @doctor.nurses.find params[:id]
    @nurse.delete
    redirect_to @nurse.nurseable
  end

  def edit
    @doctor = Doctor.find params[:id]
  end

  def update
    @doctor = Doctor.find params[:id]
    @doctor.update doctor_params
    redirect_to doctors_path
  end

  def destroy
    @doctor = Doctor.find params[:id]
    @doctor.destroy
    redirect_to doctors_path
  end


  private

  def doctor_params
    params.require(:doctor).permit(
      :doctor_name,
      :specialty
      )
  end

  def nurse_params
    params.require(:nurse).permit(
      :nurse_name
      )
  end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
/ %form.form-horizonal
/   = form_for (@doctor) do |f|
/     .form-group
/       = f.label :doctor_name, class: "col-sm-2 control-label"
/       .col-sm-10
/         = f.text_field :doctor_name, class: "form-control"
/     .form-group
/       = f.label :specialty, class: "col-sm-2 control-label"
/       .col-sm-10
/         = f.text_field :specialty, class: "form-control"
/     .form-group
/       .col-sm-offset-4.col-sm-8
/         = f.submit "Register Doctor", class: "btn btn-primary"
/   = link_to "Back to Doctor List", doctors_path

= form_for(@doctor) do |f|
  %br
  .field
    = f.label :doctor_name
    %br
      = f.text_field :doctor_name, class: "name-test"
      %span.error Please fill in name
  .field
    = f.label :specialty
    %br
      = f.text_field :specialty, class: "doctor-specialty-test"
      %span.error Please fill in specialty
    %br
  .actions
    = f.submit "Submit", class: "btn btn-primary disabled doctor-submit"

app/views/doctors/_patients.html.haml
- @patients.each do |patient|
  %ul.dl-horizontal
    %dt First Name
    %dd= patient.first_name
    %dt Last Name
    %dd= patient.last_name
    %dt Description
    %dd= patient.description
    %dt= link_to 'Patient Profile', doctor_patient_path(@doctor, patient)
    %dd

app/views/doctors/_show.html.haml
= form_tag doctor_patients_path (@doctor), method: :get, class: "navbar-form", role: "search" do
  = text_field_tag :search, params[:search]
  = submit_tag "Search", class: "patient-search"

app/views/doctors/edit.html.haml
- provide(:pagetitle, 'Edit')
= render 'form'

app/views/doctors/index.html.haml
= form_tag doctors_path, method: :get, class: "navbar-form", role: "search" do
  .input.group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-butn
      %button.btn.btn-default{:style => "width:60px"}
        %i.glyphicon.glyphicon-search


%h2 Doctor List
- @doctors.each do |d|
  %dl.dl-horizontal
    %dt Name
    %dd= d.doctor_name
    %dt Specialty
    %dd= d.specialty
    %dt
    %dd= link_to 'View Profile', doctor_path(d)
= link_to 'Add a doctor', new_doctor_path

app/views/doctors/new.html.haml
- provide(:pagetitle, 'Doctor Registration')
%h2 Add Doctor
%br/
= render 'form'

app/views/doctors/show.html.haml
%h1
  = @doctor.doctor_name
  %small= @doctor.specialty
= link_to "Edit Doctor", edit_doctor_path(@doctor), class: 'btn btn-info'
= link_to "Delete Doctor", doctor_path(@doctor), method: :delete, class: 'btn btn-danger'
%br/
%br/
%h3 Patient List
= link_to "Patient List", doctor_patients_path(@doctor), class: 'btn btn-primary'
= link_to "Add Patient", new_doctor_patient_path(@doctor), class: 'btn btn-primary'
%br/
%br/

/ $("div.content").html("#{j(render 'show')}")
/ $("div.content").html("#{j(render 'patients')}")

%br/
%br/
= form_for @nurse, url: create_nurse_doctor_path(@doctor) do |f|
  = f.label :Nurse_name
  = f.text_area :nurse_name
  %br/
  = f.submit
  = link_to "Back to Doctor List", doctors_path
  %br/
%ul
  - @nurses.each do |nurse|
    %li
      = nurse.nurse_name
      = link_to "Delete Nurse", destroy_nurse_doctor_path(nurse), method: :delete
      %br/